/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package apresentacao;

import java.awt.image.BufferedImage;
import java.io.File;
import java.io.FileInputStream;
import java.io.FileNotFoundException;
import java.io.FileOutputStream;
import java.io.IOException;
import java.io.InputStream;
import java.io.OutputStream;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import negocio.Paciente;
import persistencia.IPacienteDAO;
import persistencia.PacienteDAO;

/**
 *
 * @author andregoro
 */
public class fmPaciente extends javax.swing.JInternalFrame {
File arquivoFoto=null;
    /**
     * Creates new form fmPaciente
     */
    public fmPaciente() {
        initComponents();
    }
    public void limpar(){
        txtNome.setText("");
        txtEndereco.setText("");
        txtObservacoes.setText("");
        txtCPF.setText("");
        txtData.setText("");
        txtTelefone.setText("");
        paFoto.setText("");
    }
    public void habilitar(boolean hab){
        //btNovo
        jPanel1.setVisible(hab);
        btNovo.setEnabled(!hab);
        btSalvar.setEnabled(hab) ;
        btSair.setEnabled(hab) ;
        btUpload.setEnabled(hab) ;
        
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        paFoto = new javax.swing.JLabel();
        txtNome = new javax.swing.JTextField();
        txtEndereco = new javax.swing.JTextField();
        cbPlanoSaude = new javax.swing.JComboBox<>();
        btUpload = new javax.swing.JButton();
        rbFeminino = new javax.swing.JRadioButton();
        rbMasculino = new javax.swing.JRadioButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtObservacoes = new javax.swing.JTextArea();
        txtCPF = new javax.swing.JFormattedTextField();
        txtData = new javax.swing.JFormattedTextField();
        txtTelefone = new javax.swing.JFormattedTextField();
        btNovo = new javax.swing.JButton();
        btSalvar = new javax.swing.JButton();
        btSair = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();

        setClosable(true);
        setIconifiable(true);
        setTitle("Cadastro de Paciente");
        addInternalFrameListener(new javax.swing.event.InternalFrameListener() {
            public void internalFrameActivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosed(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosing(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeactivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeiconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameIconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameOpened(javax.swing.event.InternalFrameEvent evt) {
                formInternalFrameOpened(evt);
            }
        });

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Dados"));
        jPanel1.setToolTipText("");
        jPanel1.setLayout(null);

        jLabel1.setText("Nome Completo:");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(80, 30, 110, 20);

        jLabel2.setText("CPF:");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(140, 60, 50, 20);

        jLabel3.setText("Data de Nascimento:");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(70, 90, 120, 20);

        jLabel4.setText("Sexo:");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(140, 120, 50, 20);

        jLabel5.setText("Endereço:");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(120, 150, 70, 20);

        jLabel6.setText("Telefone:");
        jPanel1.add(jLabel6);
        jLabel6.setBounds(120, 180, 70, 20);

        jLabel7.setText("Plano de saúde:");
        jPanel1.add(jLabel7);
        jLabel7.setBounds(90, 210, 100, 20);

        jLabel8.setText("Observações:");
        jPanel1.add(jLabel8);
        jLabel8.setBounds(100, 240, 90, 20);

        jLabel9.setText("Fotografia");
        jPanel1.add(jLabel9);
        jLabel9.setBounds(510, 40, 90, 14);

        paFoto.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.add(paFoto);
        paFoto.setBounds(490, 60, 90, 90);
        jPanel1.add(txtNome);
        txtNome.setBounds(190, 30, 250, 30);
        jPanel1.add(txtEndereco);
        txtEndereco.setBounds(190, 150, 250, 30);

        cbPlanoSaude.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Amil Saúde", "Bio Saúde", "Bradesco Seguro Saúde", "Caixa Seguro Saúde", "Greenline Saúde", "Unimed Fesp" }));
        jPanel1.add(cbPlanoSaude);
        cbPlanoSaude.setBounds(190, 210, 110, 20);

        btUpload.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/recursos/Up_32.png"))); // NOI18N
        btUpload.setText("Upload");
        btUpload.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btUploadActionPerformed(evt);
            }
        });
        jPanel1.add(btUpload);
        btUpload.setBounds(481, 170, 110, 40);

        buttonGroup1.add(rbFeminino);
        rbFeminino.setText("Feminina");
        jPanel1.add(rbFeminino);
        rbFeminino.setBounds(280, 120, 90, 23);

        buttonGroup1.add(rbMasculino);
        rbMasculino.setText("Masculino");
        jPanel1.add(rbMasculino);
        rbMasculino.setBounds(190, 120, 90, 23);

        txtObservacoes.setColumns(20);
        txtObservacoes.setRows(5);
        jScrollPane2.setViewportView(txtObservacoes);

        jPanel1.add(jScrollPane2);
        jScrollPane2.setBounds(190, 240, 380, 60);

        try {
            txtCPF.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("###.###.###-##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        jPanel1.add(txtCPF);
        txtCPF.setBounds(190, 60, 140, 30);

        try {
            txtData.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        jPanel1.add(txtData);
        txtData.setBounds(190, 90, 80, 30);

        try {
            txtTelefone.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("(##)####-####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        jPanel1.add(txtTelefone);
        txtTelefone.setBounds(190, 180, 140, 30);

        btNovo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/recursos/new-32.png"))); // NOI18N
        btNovo.setText("Novo");
        btNovo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btNovoActionPerformed(evt);
            }
        });

        btSalvar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/recursos/Save_32.png"))); // NOI18N
        btSalvar.setText("Salvar");
        btSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btSalvarActionPerformed(evt);
            }
        });

        btSair.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/recursos/Exit-32.png"))); // NOI18N
        btSair.setText("Sair");
        btSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btSairActionPerformed(evt);
            }
        });

        jLabel10.setText("Cadastro de Paciente");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 631, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(134, Short.MAX_VALUE)
                .addComponent(btNovo)
                .addGap(63, 63, 63)
                .addComponent(btSalvar)
                .addGap(60, 60, 60)
                .addComponent(btSair)
                .addGap(95, 95, 95))
            .addGroup(layout.createSequentialGroup()
                .addGap(244, 244, 244)
                .addComponent(jLabel10)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(jLabel10)
                .addGap(18, 18, 18)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 326, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(40, 40, 40)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btSair)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btSalvar)
                        .addComponent(btNovo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGap(22, 22, 22))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btNovoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btNovoActionPerformed
        // TODO add your handling code here:
        habilitar(true);
        limpar();
    }//GEN-LAST:event_btNovoActionPerformed

    private void btSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btSalvarActionPerformed
        // TODO add your handling code here:
        int valor=JOptionPane.showConfirmDialog(null,"Tem certeze que deseja salvar?","Sistema Consultorio Medicos",1);
        if(valor==0){
        Paciente paciente=new Paciente();
        paciente.setNome(txtNome.getText());
        paciente.setCpf(txtCPF.getText());//2
        try{
            SimpleDateFormat data=new SimpleDateFormat("dd/MM/yyyy");
            Calendar cal = Calendar.getInstance();
            cal.setTime(data.parse(txtData.getText()));
            paciente.setData_nascimento(cal);//4
        }catch(ParseException e){
            System.out.println(e);
        }
        if(rbMasculino.isSelected()){
            paciente.setSexo("M");
        }else if(rbFeminino.isSelected()){
            paciente.setSexo("F");//
        }
        
        paciente.setEndereco(txtEndereco.getText());//6
        paciente.setTelefone(txtTelefone.getText());
        paciente.setPlano_saude(cbPlanoSaude.getSelectedItem().toString());//8
        
        String novoNomeFoto=txtNome.getText().replace(" ","")+txtNome.getText().hashCode()+".png";
        File urlFoto=new File("C:\\Users\\andregoro\\Documents\\"+novoNomeFoto);
        try{
            copiarArquivo(arquivoFoto,urlFoto);
        }catch(IOException ex){
            System.out.println("Nao foi possivel move o arquivo "+ex);
        }
        paciente.setFoto(urlFoto.getPath());
        paciente.setObservacoes(txtObservacoes.getText());
        
        IPacienteDAO dao= new PacienteDAO();
        dao.adiciona(paciente);
        JOptionPane.showConfirmDialog(null,"Os dados foram gravados");
        habilitar(false);
        limpar();
        }
//        habilitar(false);
//        limpar();
    }//GEN-LAST:event_btSalvarActionPerformed

    private void btSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btSairActionPerformed
        // TODO add your handling code here:
       this.dispose();
    }//GEN-LAST:event_btSairActionPerformed

    private void formInternalFrameOpened(javax.swing.event.InternalFrameEvent evt) {//GEN-FIRST:event_formInternalFrameOpened
        // TODO add your handling code here:
        habilitar(false);
        limpar();
    }//GEN-LAST:event_formInternalFrameOpened

    private void btUploadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btUploadActionPerformed
        // TODO add your handling code here:
        JFileChooser filechooser=new JFileChooser();
        filechooser.setDialogTitle("Escolha uma foto");
        filechooser.setFileSelectionMode(JFileChooser.FILES_ONLY);
    
        int returnval=filechooser.showOpenDialog(this);
        if(returnval==JFileChooser.APPROVE_OPTION){
            arquivoFoto=filechooser.getSelectedFile();
            BufferedImage bi;
            try{
                bi=ImageIO.read(arquivoFoto);
                JLabel imgLabel=new JLabel(new ImageIcon(bi));
                imgLabel.setSize(150, 150);
                paFoto.add(imgLabel);
                paFoto.revalidate();
                paFoto.repaint();
            }catch(IOException e){
                System.out.println("Erro na foto");
            }
            this.pack();
        }
    }//GEN-LAST:event_btUploadActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btNovo;
    private javax.swing.JButton btSair;
    private javax.swing.JButton btSalvar;
    private javax.swing.JButton btUpload;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JComboBox<String> cbPlanoSaude;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel paFoto;
    private javax.swing.JRadioButton rbFeminino;
    private javax.swing.JRadioButton rbMasculino;
    private javax.swing.JFormattedTextField txtCPF;
    private javax.swing.JFormattedTextField txtData;
    private javax.swing.JTextField txtEndereco;
    private javax.swing.JTextField txtNome;
    private javax.swing.JTextArea txtObservacoes;
    private javax.swing.JFormattedTextField txtTelefone;
    // End of variables declaration//GEN-END:variables

    private void copiarArquivo(File origem, File destino) throws FileNotFoundException, IOException {
        InputStream in =new FileInputStream(origem);
        OutputStream out=new FileOutputStream(destino);
        byte[] buf = new byte[1024];
        int len;
        while((len=in.read(buf))>0){
            out.write(buf,0,len);
        }
        in.close();
        out.close();
    }
}
